<Project Sdk="Godot.NET.Sdk/4.7.0">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="hotreload.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../libs/V12/V12.csproj"/>
    <ProjectReference Include="../libs/V12.Basic/V12.Basic.csproj"/>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="addons\" />
  </ItemGroup>
</Project>